#pragma once

// Generated by tools/generate_tiago_dynamics.py from the native Tiago URDF.
// These limits are the raw URDF limits for the right arm. Safety margins belong
// in solver policy/tuning code, not in this source-of-truth robot data.

namespace gato {
namespace plant {

        constexpr int TIAGO_LIMIT_JOINTS = 7;

        template<class T>
        __device__ constexpr T JOINT_LIMITS_DATA[TIAGO_LIMIT_JOINTS][2] = {
            {static_cast<T>(-4.7123889803846897), static_cast<T>(0.52359877559829882)},  // arm_right_1_joint
            {static_cast<T>(-2.4434609527920612), static_cast<T>(1.1344640137963142)},  // arm_right_2_joint
            {static_cast<T>(-2.6179938779914944), static_cast<T>(2.6179938779914944)},  // arm_right_3_joint
            {static_cast<T>(-2.4434609527920612), static_cast<T>(1.1344640137963142)},  // arm_right_4_joint
            {static_cast<T>(-1.5707963267948966), static_cast<T>(3.6651914291880923)},  // arm_right_5_joint
            {static_cast<T>(-1.8849555921538759), static_cast<T>(3.001966313430247)},  // arm_right_6_joint
            {static_cast<T>(-2.6179938779914944), static_cast<T>(2.6179938779914944)},  // arm_right_7_joint
        };

        template<class T>
        __device__ constexpr T VEL_LIMITS_DATA[TIAGO_LIMIT_JOINTS][2] = {
            {static_cast<T>(-2.5), static_cast<T>(2.5)},  // arm_right_1_joint
            {static_cast<T>(-2.5), static_cast<T>(2.5)},  // arm_right_2_joint
            {static_cast<T>(-2.5), static_cast<T>(2.5)},  // arm_right_3_joint
            {static_cast<T>(-2.5), static_cast<T>(2.5)},  // arm_right_4_joint
            {static_cast<T>(-2.5), static_cast<T>(2.5)},  // arm_right_5_joint
            {static_cast<T>(-2.5), static_cast<T>(2.5)},  // arm_right_6_joint
            {static_cast<T>(-2.5), static_cast<T>(2.5)},  // arm_right_7_joint
        };

        template<class T>
        __device__ constexpr T CTRL_LIMITS_DATA[TIAGO_LIMIT_JOINTS][2] = {
            {static_cast<T>(-43), static_cast<T>(43)},  // arm_right_1_joint
            {static_cast<T>(-43), static_cast<T>(43)},  // arm_right_2_joint
            {static_cast<T>(-26), static_cast<T>(26)},  // arm_right_3_joint
            {static_cast<T>(-26), static_cast<T>(26)},  // arm_right_4_joint
            {static_cast<T>(-26), static_cast<T>(26)},  // arm_right_5_joint
            {static_cast<T>(-26), static_cast<T>(26)},  // arm_right_6_joint
            {static_cast<T>(-26), static_cast<T>(26)},  // arm_right_7_joint
        };

        template<class T>
        __host__ __device__ constexpr const T (&JOINT_LIMITS())[TIAGO_LIMIT_JOINTS][2]
        {
                return JOINT_LIMITS_DATA<T>;
        }

        template<class T>
        __host__ __device__ constexpr const T (&VEL_LIMITS())[TIAGO_LIMIT_JOINTS][2]
        {
                return VEL_LIMITS_DATA<T>;
        }

        template<class T>
        __host__ __device__ constexpr const T (&CTRL_LIMITS())[TIAGO_LIMIT_JOINTS][2]
        {
                return CTRL_LIMITS_DATA<T>;
        }

}  // namespace plant
}  // namespace gato
